### ISSUE TITLE
SRP and UoW in Chapter 7

### ISSUE THREAD

**Issue by jonathanmeier5** [python-leap/book#101]
I might be being far too pedantic here, but does our UoW violate the single responsibility principle by the end of Chapter 7?

It's now responsible for committing changes and handling events, which seems to flag the tip earlier in the chapter about and/then watch words.

Is this just an acceptable cost of doing business?

**Comment by bobthemighty** [comment]
Uh... yee-ish? 

Its responsibility really is to _manage a set of related changes that have to happen together_. It so happens that there are important two bits to that: committing changes to a database session, and raising events that happened as a result.

**Comment by jonathanmeier5** [comment]
Like I said, far too pedantic. :) Thanks for clarifying. Closing.
