### ISSUE TITLE
Chapter 7 - One Simple Option

### ISSUE THREAD

**Issue by mr-bo-jangles** [python-leap/book#104]
At https://github.com/python-leap/book/blob/master/chapter_07_events_and_message_bus.asciidoc#one-simple-option-the-service-layer-puts-events-on-the-message-bus in example 8 there is an exception raised however you mentioned previously that Events and Exceptions don't mix. This somewhat confused me and it'd be nice to get some reassurance via your patented  comment footnotes that this is intended.

P.s. Loving the book so far, although I can now never look at my work's codebase the same way again...

**Comment by mr-bo-jangles** [comment]
Being totally nitpicky, Example 10, `def get` should follow the convention of the product instance being assigned to `product` instead of `p`.

**Comment by hjwp** [comment]
thanks for this!  where do you work out of interest?  we're very interested in the practical difficulties people foresee in implementing this stuff in actual code. we want to make sure we address common questions in the "how do i get there from here" chapter we have planned for the end of the book...

**Comment by mr-bo-jangles** [comment]
@hjwp I've emailed you with the answer to that
