### ISSUE TITLE
Chapter 11 - Captain Quakers Raging Seizures

### ISSUE THREAD

**Issue by mr-bo-jangles** [python-leap/book#107]
You've got to be getting sick of me by now >.>

Example 7 - You have two separate handlers on a single event, each with a separate UoW. What happens if the latter of the two fails due to my inability to operate after reading architecture githubs all night? Is this something you could detect and later recover from or are we trusting my shaky testing ability entirely to catch issues pre-production?

**Comment by hjwp** [comment]
great question!  @bob we definitely need that section on error-handling for events vs commands...

**Comment by bobthemighty** [comment]
Which chapter does that belong in? I've been fiddling a bit with chapter 7.

On an unrelated note chapter 8 is _great_.

**Comment by hjwp** [comment]
chapter 9.  but we can put some pointers to it in 7 and 8.

**Comment by hjwp** [comment]
we've got a good bit on error-handling in 9 now :)
