### ISSUE TITLE
Django guide posts

### ISSUE THREAD

**Issue by bobthemighty** [python-leap/book#11]
LEt's add some sidebars for Django developers to explain how these concepts map back to the framework they know and ... know

**Comment by LuRsT** [comment]
I'd love if there was some advice on how to mold such an opinionated framework into something closer to a "clean architecture"

**Comment by hjwp** [comment]
did you see the django appendix?  https://github.com/python-leap/book/blob/master/appendix_django.asciidoc

**Comment by LuRsT** [comment]
I've recently started to read the book again and was pleased to see a link to it, but I haven't read that yet, no spoilers please :hear_no_evil: ! But I didn't know it at the time of my comment, so thanks for the heads up :+1:

**Comment by hjwp** [comment]
do reopen if you have suggestions to do more!
