### ISSUE TITLE
Integration with an existing system

### ISSUE THREAD

**Issue by daniel-butler** [python-leap/book#122]
Given that there is any existing ordering system how would we integrate that with the product allocation system that’s been created?

Would an option be a translation layer between the existing system and the new allocation system? What would that look like?

The focus of the book is how to apply the concepts internally maybe a hint of how to handle external events would be seen as valuable. (I know it is for me since that’s something I’m struggling with as I’m working though a project using the ideas in the book). I can’t say it enough love the book!

**Comment by hjwp** [comment]
Hi Daniel!  Have you got as far as the "external events" chapter yet? (chap 10 i think).  The way we integrate most of our systems at MADE is using an event-driven model, async/pubsub sort of thing.

In the book when we start out we're building an API, imagining the ordering system would call the allocation system synchronously.  But in chapter 10 we show the example of integrating with a logistics/shipping system that would want to provide updates on Batch ETAs and quantity changes.  We imagine this integration happening via events -- the logistics system would publish a `BatchQuantityChanged` event to some centralised events database (we use redis as an example), and then our allocation subscribes to those events, and reacts to them as appropriate, publshing any updated information (eg an `OrderLineAllocated` event) back to the same events database for other systems to listen to.

Can you see that working for you in real life?  You'd have to set up a centralised events publishing system (we use "eventstore" at MADE), and then decide on what events you need, and what info those events need to contain, for your various systems to talk to each other.

**Comment by daniel-butler** [comment]
I do remember opening up event store and thinking I need to look into it. I very well could have missed it. I’ll look over the chapter where you introduce redis again. 

I’ve found I read a chapter. Think I get it.  Try to implement it, realize I don’t know what I’m doing. Reread almost the entire book then it starts to click, move on to the next concept and repeat.

**Comment by hjwp** [comment]
one of these two talks may also be a good frame of reference (i haven't seen either of these, but i saw Ian giving a similar talk at a conference earlier this year.  Ian is Bob's old mentor.)

https://www.youtube.com/watch?v=PreAnSofAsA

https://www.youtube.com/watch?v=zeMEKwsK7fI

**Comment by hjwp** [comment]
(do reopen if you think there's anything we can do in the book to clarify or highlight the explanation?)
