### ISSUE TITLE
What is the point of all these patterns?

### ISSUE THREAD

**Issue by abdullahariff** [python-leap/book#21]
Here's a thought: a Python developer walks into Waterstones and sees this nice new book by Bob and Harry. Oh, he says, that looks interesting!

After picking it up he sees all these patterns for managing complexity, but they seem to have a lot of moving parts. What are they all for he wonders? How exactly will it help me manage complexity? Should I buy this book?

**Comment by hjwp** [comment]
:+1: we definitely need a bit more of a "why even bother" message, i think maybe up-front and then at the end of each part?  Bob and I were talking about this the other day actually.... thanks Abdullah...

**Comment by hjwp** [comment]
closing this following our IRL conversation about the latest draft -- do re-open, or open new issues, if you ever find yourself wondering what the point is again?
