### ISSUE TITLE
context diagram for allocation

### ISSUE THREAD

**Issue by hjwp** [python-leap/book#22]

**Comment by bobthemighty** [comment]
IS this covered by the prologue? I think we also want a diagram to show how the domain model fits together.

**Comment by hjwp** [comment]
we do have a delightful diagram for the model here https://github.com/python-leap/book/blob/master/chapter_01_domain_model.asciidoc#user-content-model_diagram

i think some sort of picture to describe what allocation is would be a good idea.  doesn't have to be a context diagram per se...

**Comment by hjwp** [comment]
some sort of visual with order, orderlines on one side, batches (maybe grouped by shipment/warehouse) on the other, and allocation in the middle.  possibly showing the outtput, an "allocation", which maps an order line to a batch.
