### ISSUE TITLE
exercises for the reader (with links to GH)

### ISSUE THREAD

**Issue by hjwp** [python-leap/book#34]
link to a broken/unfinished version of the repo for that chapter, suggest ppl implement some feature for themselves...

- [x] chapter 1: some placeholder tests, just test function names, an empty file to import from, a makefile to run the tests
- [x] chapter 2: implement a repository without an ORM?
- [x] chapter 3: add new service, `deallocate`
- [x] chapter 4 uow: maybe implement the uows? give them the codebase without the real uow, and without the fake uow?
- [x] chapter 5 aggregate: give them the repo without the aggregate, ask them to build it, and the orm.

**Comment by hjwp** [comment]
chapter 1: some placeholder tests, just test function names, an empty file to import from, a makefile to run the tests

chapter 2: implement a repository without an ORM?

chapter 3: maybe add_stock?

chapter 4 uow: maybe implement some repositories? give them the codebase without the real uow, and without the fake uow?

chapter 5 aggregate: give them the repo without the aggregate, ask them to build it, and the orm.

**Comment by hjwp** [comment]
also appendix_csvs is a great exercise on its own

**Comment by LuRsT** [comment]
What about a shopping basket? @bobthemighty will love it

**Comment by hjwp** [comment]
haha. we're actually not planning to do eventsourcing in this book.  well, not currently at least.
