### ISSUE TITLE
Chapter 10 + appendix feedback on DI

### ISSUE THREAD

**Issue by jamesjrg** [python-leap/book#40]
Chapter 10 talks of injecting dependencies into command handlers (email sender, redis, etc).

Appendix A talks about 2 different ways of handling dependencies in domain code. One option is functional core/imperative shell, and have push the use of dependencies out of domain modules altogether. The other is Bob-style injection of abstracted dependencies into the domain code.

I like the contrast of Bob vs Harry approaches in the appendix, but wonder if maybe it could be merged into chapter 10, and related to the code in all the previous chapters?

In my head at least, the combination of aggregates/service layers/command handlers/event handlers and all the rest means leads to a design that is inherently FC/IS. Command handlers take some dependencies, then call domain logic on aggregates which have no dependencies. The command handlers then take some imperative actions with the results (e.g. database updates), whilst also delegating other imperative actions to message bus handlers (e.g. sending email). So the patterns described in the book are in a way a guide to how to do FC/IS in business application development - you have imperative command handlers + event handlers, and functional domain logic.

This in turn has the advantages of easy testing described in appendix A, as well as making it easier to read and reason about domain logic without being waylaid by having to consider the order of database updates or where values are being cached.

**Comment by hjwp** [comment]
absolutely!  and actually, i think the architecture we're presenting actually has us doing _both_.  we have a functional core at the model layer, but the (imperative) service/handlers layer uses DI to get its dependencies, which means it's unit-testable as well.

**Comment by hjwp** [comment]
i think merging the abstractions appendix into chapter 10 would mean that people read later than we want though. we're actually thinking of making the abstractions chapter into a "proper" chapter, maybe even chapter 3, straight after repository pattern. 

In the meantime, I'm making a note to talk about whether our architecture is FCIS or DI or both, in the appendix, and I'll add a link back to that appendix from the DI chapter.
