### ISSUE TITLE
Ch 2 Comments

### ISSUE THREAD

**Issue by xtaje** [python-leap/book#42]
* https://github.com/python-leap/book/blame/master/chapter_02_repository.asciidoc#L459
Someone in the audience of my mocking talk at PyCon asked if doing dependency injection would require defining and deriving IWhatever interfaces everywhere. My answer was that in Python you can rely on duck-typing. (I am unsure how well this plays out with type annotations). It may be worth calling out explicitly what you would do instead of ABCs.

* https://github.com/python-leap/book/blame/master/chapter_02_repository.asciidoc#L193

For comparison sake, [Protobuf](https://developers.google.com/protocol-buffers/docs/pythontutorial) suggests handling this problem with composition.  Might be a useful sidebar.
> Protocol Buffers and O-O Design Protocol buffer classes are basically dumb data holders (like structs in C); they don't make good first class citizens in an object model. If you want to add richer behaviour to a generated class, the best way to do this is to wrap the generated protocol buffer class in an application-specific class. Wrapping protocol buffers is also a good idea if you don't have control over the design of the .proto file (if, say, you're reusing one from another project). In that case, you can use the wrapper class to craft an interface better suited to the unique environment of your application: hiding some data and methods, exposing convenience functions, etc. You should never add behaviour to the generated classes by inheriting from them. This will break internal mechanisms and is not good object-oriented practice anyway.

* https://github.com/python-leap/book/blame/master/chapter_02_repository.asciidoc#L273

Maybe a good opportunity to reinforce some language by saying something like, "The ORM imports (or "depends on" or "knows about") the domain model, and not the other way around.

* Misc. 
I would find having an object or class diagram (or maybe ER diagram) upfront helpful to keep the classes, objects, and tables straight in my mind.

**Comment by bobthemighty** [comment]
>  It may be worth calling out explicitly what you would do instead of ABCs.
:+1: In practice the answer is "nothing, we just rely on duck typing and prayer".

> For comparison sake, Protobuf suggests handling this problem with composition. Might be a useful sidebar.
Not a bad suggestion. Maybe there's a tie-in to the Django narrative here. I've seen people do the same with their existing active record ORM.
