### ISSUE TITLE
Ch 4 Comments

### ISSUE THREAD

**Issue by xtaje** [python-leap/book#44]
---

https://github.com/python-leap/book/blame/master/chapter_04_uow.asciidoc#L235
This is another good opportunity to drive home the idea of roles and collaborations. UOW and Repository are collaborators.

---
https://github.com/python-leap/book/blame/master/chapter_04_uow.asciidoc#L238
Maybe "Only mock your immediate neighbors" is more applicable? 

I think of "Don't mock what you don't own" as referring specifically to "mock verification" (e.g. assert mock_session.commit.assert_called_once()), with the reason for this advice being that you cannot change those interfaces.  So the mock has no value in providing feedback to your design. 

---
https://github.com/python-leap/book/blame/master/chapter_04_uow.asciidoc#L437
This was confusing, since the Product class doesn't get introduced until Chapter 5.

**Comment by bobthemighty** [comment]
> https://github.com/python-leap/book/blame/master/chapter_04_uow.asciidoc#L437
> This was confusing, since the Product class doesn't get introduced until Chapter 5.

Hi @xtaje . I'm afraid I don't follow - what was confusing here?

**Comment by hjwp** [comment]
sorry bob, i already fixed it. remove a reference to `Product` and replaced it with a batch.

**Comment by xtaje** [comment]
Looks like linking to the git blame is not a good way to leave comments.
