### ISSUE TITLE
Appendix Project Structure Comments (ej)

### ISSUE THREAD

**Issue by xtaje** [python-leap/book#52]
---
https://github.com/python-leap/book/blame/master/appendix_project_structure.asciidoc#L73

Just dropping this [pytest layout suggestions](https://docs.pytest.org/en/latest/goodpractices.html#choosing-a-test-layout-import-rules) link for reference.

---

https://github.com/python-leap/book/blame/master/appendix_project_structure.asciidoc#L57

We have separate images for tests, using [multistage builds and named stages](https://docs.docker.com/develop/develop-images/multistage-build/)
and generally it has been straightforward. Prior to multistage it was rather
complicated and we did not bother.

---

https://github.com/python-leap/book/blame/master/appendix_project_structure.asciidoc#L114

Would you consider this a singleton? 

I have some past negative experiences with this style of configuration, because it can be easily abused.  The env var mitigates against that, and I suppose this varies from codebase to codebase.

**Comment by bobthemighty** [comment]
> Would you consider this a singleton?

Not strictly. It's possible to create more than one of them, but it's unlikely that I'd do so outside of unit tests. I more or less think of these config classes as part of my composition root. They tend only to be used by the entry point to the application.

I definitely wouldn't be reaching out to the config module from all over the codebase, because I'd see that as a Service Locator pattern. If I needed to use some configured value in a use-case, I'd usually inject it alongside the other dependencies.

> We have separate images for tests, using multistage builds

Good shout. I've been doing the same for the last few months, but different teams at MADE have different practices.

**Comment by xtaje** [comment]
"Entry point to the application" is key, I think.  The anti-pattern I've seen is where the config just gets imported anywhere, and anything remotely related to configuration gets put in there.

One other thought came to mind about this chapter.  I would wager that most readers will be unfamiliar with crosscuts, or where they came from.  I'm unsure if the "Abstractions" chapter will touch on it, but it could be a good sidebar to into separation of concerns.  Then maybe you could even tie that back into DDD context maps.

**Comment by bobthemighty** [comment]
> One other thought came to mind about this chapter...

Could you clarify your meaning in this paragraph? I'm not getting it, I'm afraid :)

**Comment by xtaje** [comment]
> > One other thought came to mind about this chapter...
> 
> Could you clarify your meaning in this paragraph? I'm not getting it, I'm afraid :)

I think that the idea of "cross-cutting concerns" will be new to a lot of readers, and it hasn't been introduced anywhere in the text.  _If you wanted to_, the chapter(s) where you introduce different ways of organizing abstractions might be a good place to do it.  The basic gist would be that some things aren't so easily encapsulated or decoupled (logging, locking, circuit-breakers, etc.).

Talking about DDD context maps is probably too much of a digression, since there's only minimal discussion of bounded contexts.  But my thinking was that models in different contexts are different aspects of a concern, and the mapping forms a kind of crosscut.
