### ISSUE TITLE
Use multistage build for tests

### ISSUE THREAD

**Issue by bobthemighty** [python-leap/book#53]
per #52 we should probably use a multistage build rather than including unit tests in the production image.

**Comment by hjwp** [comment]
someone's changed their tune!  not sure multistage builds helps, but we could build two images i guess.

**Comment by xtaje** [comment]
In this specific example, it probably doesn't make that much of a difference.  The places where it really comes in handy is when you want to use one image to build something like a jar, then copy the jar out to the final image.  For the purposes of the book I am not sure what's better.

**Comment by hjwp** [comment]
using multiple images, one base/production and one base+tests, is still a possibility.  @bobthemighty do we want to present that, in use, as "best practice", or just mention it as an idea?

**Comment by hjwp** [comment]
I've updated the recommendation for minimising the number of images to leave more room for people to decide on the trade-offs for themselves.  going to close this now, if y'all feel strongly about it do re-open!
