### ISSUE TITLE
Build everything using Docker

### ISSUE THREAD

**Issue by hajs** [python-leap/book#68]
Hello, I really like your book so far :smiley: 

I wrote the following commands to build html- and pdf-versions of the source.
Maybe some instructions like that would be helpful for some other readers, too?
 
```
test -d book && (cd book; git pull) || git clone https://github.com/python-leap/book.git
docker run -it -v $(readlink -f book):/book fedora  bash -c "yum install -y make python2 ruby; \
  gem install asciidoctor; \
  gem install --pre asciidoctor-pdf; \
  gem install pygments.rb; \
  gem install asciidoctor-diagram; \
  python2 -m pip install --user pygments; \
  cd /book; make html; \
  asciidoctor-pdf -a source-highlighter=pygments -a '!example-caption' *.asciidoc;
"
```

**Comment by hjwp** [comment]
Thanks!  how much have you read?

For now, we're keeping the free/online version kinda secret, so i don't think we want to be too public with instructions on how to render your own tbh.  Will save these away for when we go to release :)
